### DISCUSSION TITLE
Add ways to allow own code detection to be added

### DISCUSSION THREAD

**Discussion by TomHart** [composer-unused/composer-unused#618] [Ideas]
We have a lot of Symfony code, wired in `.yml` files, which is currently not being detected. It'd be good to be able to add to the classes this finds so we don't need to manually exclude them

**Comment by icanhazstring** [comment]
Hi. Can you elaborate more on that so that I can get a better understanding of your needs?

**Comment by TomHart** [comment]
Yeah sure, so say for example my repo is a Symfony bundle, and I have:

```
"abc/my-package": "1.2.3"
```

and the only usage is in some YAML configuration for the bundle:

```yaml
    service:
        class: MyBundle\SomeClass
        tags: 
          - { name: something, class: Abc\MyPackage\Class }
```

In this case the package is required, but this tool doesn't detect it's usage, I'm assuming because it's just in a YAML file, not PHP.

So it'd be good to be able to somehow get it to detect this case
