### ISSUE TITLE
Namespaces of vendor aren't analyzed in config files of Symfony

### ISSUE THREAD

**Issue by fre5h** [composer-unused/composer-unused#73]
## Describe the bug
I've installed your tool for the first time on my symfony project. In my project I use such bundles and libraries: `oneup/flysystem-bundle`, `superbalist/flysystem-google-storage`, `google/cloud`. It is needed to upload files to Google Cloud Storage.

Files from `google/cloud` aren't used anywhere in my code directly. They are only described once in the settings of `oneup/flysystem-bundle`. Here is how config looks like
```yaml
oneup_flysystem:
    adapters:
        file_adapter:
            googlecloudstorage:
                client: Google\Cloud\Storage\StorageClient
                bucket: Google\Cloud\Storage\Bucket
                prefix: ~
    filesystems:
        file_fs:
            adapter: file_adapter
            mount: file_fs
            visibility: public
```

As you can this, this library is used only in config files, but it is required any way. And any other package in composer.json haven't it in required section of composer.json :(

## Additional information
I understand that it is not really a bug, and can be discussed. Maybe you can suggest something. RIght now I've added `google/cloud` to the extra parameters on composer.json
```
    "extra": {
        "unused": [
            "google/cloud"
        ]
    }
```
I think it can be solved like an additional plugin for Symfony, which also analyzes dependencies from config files.
