### ISSUE TITLE
False positive for ramsey/uuid-doctrine and beberlei/doctrineextensions

### ISSUE THREAD

**Issue by VincentLanglet** [composer-unused/composer-unused#74]
## Describe the bug
The https://github.com/ramsey/uuid-doctrine and https://github.com/beberlei/doctrineextensions is reported as unused in my symfony project.

But I do used them. This way
```
doctrine:
    dbal:
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
    orm:
        dql:
            datetime_functions:
                DATEDIFF: DoctrineExtensions\Query\Mysql\DateDiff
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
                MONTH: DoctrineExtensions\Query\Mysql\Month
                NOW: DoctrineExtensions\Query\Mysql\Now
                SEC_TO_TIME: DoctrineExtensions\Query\Mysql\SecToTime
                TIMEDIFF: DoctrineExtensions\Query\Mysql\TimeDiff
                TIME_TO_SEC: DoctrineExtensions\Query\Mysql\TimeToSec
                WEEK: DoctrineExtensions\Query\Mysql\Week
                YEAR: DoctrineExtensions\Query\Mysql\Year
                YEARWEEK: DoctrineExtensions\Query\Mysql\YearWeek
            numeric_functions:
                FLOOR: DoctrineExtensions\Query\Mysql\Floor
                NULLIF: DoctrineExtensions\Query\Mysql\NullIf
            string_functions:
                SOUNDEX: DoctrineExtensions\Query\Mysql\Soundex
```

Can this project handle yaml config ?
